[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "biome"]
formatter = { command = "biome" , args = ["format", "--stdin-file-path=file.ts"] }

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "biome"]
formatter = { command = "biome" , args = ["format", "--stdin-file-path=file.js"] }

[[language]]
name = "javascript"
formatter = { command = "biome" , args = ["format", "--stdin-file-path=file.json"] }
