modal = true
default_flags = "g"
show_selection_mark = true

[[verbs]]
invocation = "open"
key = "enter"
external = "nu ~/.local/share/scripts/ide.nu open-file '{file}'"
apply_to = "file"
leave_broot = false

[[verbs]]
invocation = "touch {name}"
external = "nu -c \"touch {directory}/{name}\""
apply_to = "any"
leave_broot = false
